package icu.hao.haomall.model.dao;

import icu.hao.haomall.model.pojo.Cart;
import org.springframework.stereotype.Repository;

@Repository
public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hao_mall_cart
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hao_mall_cart
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    int insert(Cart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hao_mall_cart
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    int insertSelective(Cart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hao_mall_cart
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hao_mall_cart
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    int updateByPrimaryKeySelective(Cart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hao_mall_cart
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    int updateByPrimaryKey(Cart row);
}