package icu.hao.haomall.model.dao;

import icu.hao.haomall.model.pojo.Category;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hao_mall_category
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hao_mall_category
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    int insert(Category row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hao_mall_category
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    int insertSelective(Category row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hao_mall_category
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    Category selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hao_mall_category
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    int updateByPrimaryKeySelective(Category row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hao_mall_category
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    int updateByPrimaryKey(Category row);

    Category selectByName(String name);

    List<Category> selectList();
    List<Category> selectByParentId(Integer parentId);
}