package icu.hao.haomall.model.dao;

import icu.hao.haomall.model.pojo.Order;
import org.springframework.stereotype.Repository;

@Repository
public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hao_mall_order
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hao_mall_order
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    int insert(Order row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hao_mall_order
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    int insertSelective(Order row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hao_mall_order
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hao_mall_order
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    int updateByPrimaryKeySelective(Order row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hao_mall_order
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    int updateByPrimaryKey(Order row);
}