package icu.hao.haomall.model.dao;

import icu.hao.haomall.model.pojo.OrderItem;
import org.springframework.stereotype.Repository;

@Repository
public interface OrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hao_mall_order_item
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hao_mall_order_item
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    int insert(OrderItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hao_mall_order_item
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    int insertSelective(OrderItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hao_mall_order_item
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    OrderItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hao_mall_order_item
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    int updateByPrimaryKeySelective(OrderItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hao_mall_order_item
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    int updateByPrimaryKey(OrderItem row);
}