package icu.hao.haomall.model.pojo;

import java.util.Date;

public class Cart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hao_mall_cart.id
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hao_mall_cart.product_id
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hao_mall_cart.user_id
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hao_mall_cart.quantity
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hao_mall_cart.selected
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    private Integer selected;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hao_mall_cart.create_time
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hao_mall_cart.update_time
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hao_mall_cart.id
     *
     * @return the value of hao_mall_cart.id
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hao_mall_cart.id
     *
     * @param id the value for hao_mall_cart.id
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hao_mall_cart.product_id
     *
     * @return the value of hao_mall_cart.product_id
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hao_mall_cart.product_id
     *
     * @param productId the value for hao_mall_cart.product_id
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hao_mall_cart.user_id
     *
     * @return the value of hao_mall_cart.user_id
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hao_mall_cart.user_id
     *
     * @param userId the value for hao_mall_cart.user_id
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hao_mall_cart.quantity
     *
     * @return the value of hao_mall_cart.quantity
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hao_mall_cart.quantity
     *
     * @param quantity the value for hao_mall_cart.quantity
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hao_mall_cart.selected
     *
     * @return the value of hao_mall_cart.selected
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public Integer getSelected() {
        return selected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hao_mall_cart.selected
     *
     * @param selected the value for hao_mall_cart.selected
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public void setSelected(Integer selected) {
        this.selected = selected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hao_mall_cart.create_time
     *
     * @return the value of hao_mall_cart.create_time
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hao_mall_cart.create_time
     *
     * @param createTime the value for hao_mall_cart.create_time
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hao_mall_cart.update_time
     *
     * @return the value of hao_mall_cart.update_time
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hao_mall_cart.update_time
     *
     * @param updateTime the value for hao_mall_cart.update_time
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}