package icu.hao.haomall.model.pojo;

import java.util.Date;

public class OrderItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hao_mall_order_item.id
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hao_mall_order_item.order_no
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hao_mall_order_item.product_id
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hao_mall_order_item.product_name
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hao_mall_order_item.product_image
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    private String productImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hao_mall_order_item.unit_price
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    private Integer unitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hao_mall_order_item.quantity
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hao_mall_order_item.total_price
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    private Integer totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hao_mall_order_item.create_time
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hao_mall_order_item.update_time
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hao_mall_order_item.id
     *
     * @return the value of hao_mall_order_item.id
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hao_mall_order_item.id
     *
     * @param id the value for hao_mall_order_item.id
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hao_mall_order_item.order_no
     *
     * @return the value of hao_mall_order_item.order_no
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hao_mall_order_item.order_no
     *
     * @param orderNo the value for hao_mall_order_item.order_no
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hao_mall_order_item.product_id
     *
     * @return the value of hao_mall_order_item.product_id
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hao_mall_order_item.product_id
     *
     * @param productId the value for hao_mall_order_item.product_id
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hao_mall_order_item.product_name
     *
     * @return the value of hao_mall_order_item.product_name
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hao_mall_order_item.product_name
     *
     * @param productName the value for hao_mall_order_item.product_name
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hao_mall_order_item.product_image
     *
     * @return the value of hao_mall_order_item.product_image
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public String getProductImage() {
        return productImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hao_mall_order_item.product_image
     *
     * @param productImage the value for hao_mall_order_item.product_image
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public void setProductImage(String productImage) {
        this.productImage = productImage == null ? null : productImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hao_mall_order_item.unit_price
     *
     * @return the value of hao_mall_order_item.unit_price
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public Integer getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hao_mall_order_item.unit_price
     *
     * @param unitPrice the value for hao_mall_order_item.unit_price
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public void setUnitPrice(Integer unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hao_mall_order_item.quantity
     *
     * @return the value of hao_mall_order_item.quantity
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hao_mall_order_item.quantity
     *
     * @param quantity the value for hao_mall_order_item.quantity
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hao_mall_order_item.total_price
     *
     * @return the value of hao_mall_order_item.total_price
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public Integer getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hao_mall_order_item.total_price
     *
     * @param totalPrice the value for hao_mall_order_item.total_price
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public void setTotalPrice(Integer totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hao_mall_order_item.create_time
     *
     * @return the value of hao_mall_order_item.create_time
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hao_mall_order_item.create_time
     *
     * @param createTime the value for hao_mall_order_item.create_time
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hao_mall_order_item.update_time
     *
     * @return the value of hao_mall_order_item.update_time
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hao_mall_order_item.update_time
     *
     * @param updateTime the value for hao_mall_order_item.update_time
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}