package icu.hao.haomall.model.pojo;

import java.util.Date;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hao_mall_product.id
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hao_mall_product.name
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hao_mall_product.image
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hao_mall_product.detail
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hao_mall_product.category_id
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hao_mall_product.price
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hao_mall_product.stock
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hao_mall_product.status
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hao_mall_product.create_time
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hao_mall_product.update_time
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hao_mall_product.id
     *
     * @return the value of hao_mall_product.id
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hao_mall_product.id
     *
     * @param id the value for hao_mall_product.id
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hao_mall_product.name
     *
     * @return the value of hao_mall_product.name
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hao_mall_product.name
     *
     * @param name the value for hao_mall_product.name
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hao_mall_product.image
     *
     * @return the value of hao_mall_product.image
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hao_mall_product.image
     *
     * @param image the value for hao_mall_product.image
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hao_mall_product.detail
     *
     * @return the value of hao_mall_product.detail
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hao_mall_product.detail
     *
     * @param detail the value for hao_mall_product.detail
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hao_mall_product.category_id
     *
     * @return the value of hao_mall_product.category_id
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hao_mall_product.category_id
     *
     * @param categoryId the value for hao_mall_product.category_id
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hao_mall_product.price
     *
     * @return the value of hao_mall_product.price
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hao_mall_product.price
     *
     * @param price the value for hao_mall_product.price
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hao_mall_product.stock
     *
     * @return the value of hao_mall_product.stock
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hao_mall_product.stock
     *
     * @param stock the value for hao_mall_product.stock
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hao_mall_product.status
     *
     * @return the value of hao_mall_product.status
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hao_mall_product.status
     *
     * @param status the value for hao_mall_product.status
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hao_mall_product.create_time
     *
     * @return the value of hao_mall_product.create_time
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hao_mall_product.create_time
     *
     * @param createTime the value for hao_mall_product.create_time
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hao_mall_product.update_time
     *
     * @return the value of hao_mall_product.update_time
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hao_mall_product.update_time
     *
     * @param updateTime the value for hao_mall_product.update_time
     *
     * @mbg.generated Tue May 21 01:26:00 AEST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}